parameters:
  environment: 'NOT_DEFINED'
  dotnetVersion: 'NOT_DEFINED'
  buildConfiguration: 'Debug'
  artifactName: 'drop'

jobs:
- job:
  displayName: dotnet - build & publish - ${{ parameters.environment }}
  steps:
  - task: UseDotNet@2
    displayName: use dotnet ${{ parameters.dotnetVersion }}
    inputs:
      version: '${{ parameters.dotnetVersion }}'

  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '-c ${{ parameters.buildConfiguration }} --no-restore'

  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '-o $(Build.ArtifactStagingDirectory) -c ${{ parameters.buildConfiguration }} --no-build'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: publish artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${{ parameters.artifactName }}'
      publishLocation: 'Container'
    